version: '3.9'

networks:
    local:

services:
    database:
        image: mysql:8
        ports:
            - 3306:3306
        volumes:
            - ./data/db:/var/lib/mysql
        networks:
            - local
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
